CREATE TABLE IF NOT EXISTS pos_data (
  id INT NOT NULL PRIMARY KEY,
  payload LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pos_users (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  username VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(200) NOT NULL DEFAULT '',
  role VARCHAR(32) NOT NULL,
  disabled TINYINT(1) NOT NULL DEFAULT 0,
  permissions JSON NULL,
  created_at DATETIME NULL,
  UNIQUE KEY uq_pos_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
